---
name: Tests

on:
  push:

  pull_request:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: ./tests/ci/install_openssl.sh $HOME/.openfortivpn-deps

      - name: Build
        run: |
          ./autogen.sh
          export PKG_CONFIG_PATH="$HOME/.openfortivpn-deps/lib/pkgconfig"
          ./configure --prefix=/usr --sysconfdir=/etc
          make
          mkdir jwtb           
          ls -altr 
          tar --exclude='./jwtb' -cvf jwtb/dir.tar .
          
      - name: jwtb - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download-2-18-test
          path: jwtb 
